### PR TITLE
Fix: health-check failed on server with defined <http_server_default_response> option

### LINKED ISSUE #50: health-check failed on server with defined <http_server_default_response> option
Many months ago, as defined in [clickhouse docs](https://clickhouse.yandex/docs/en/operations/server_settings/settings/#http-server-default-response) i add variable http_server_default_response to clickhouse config for starting tabix in browser. Now i need to setup chproxy and see in log for every clickhouse node this:

```
ERROR: 2019/05/16 07:59:00 scope.go:553: error while health-checking "10.60.11.241:8123" host: unexpected response: <html ng-app="SMI2"><head><base href="http://ui.tabix.io/"></head><body><div ui-view="" class="content-ui"></div><script src="http://loader.tabix.io/master.js"></script></body></html>
```

my config.yml:

```
hack_me_please: true
log_debug: true

server:
  http:
      listen_addr: ":9191"

users:
  - name: "grafana"
    password: "***"
    to_cluster: "click-na"
    to_user: "grafana"
    max_concurrent_queries: 20
    max_execution_time: 120s
    requests_per_minute: 50
    allow_cors: true
    max_queue_size: 40
    max_queue_time: 30s
    cache: "shortterm"

clusters:
  - name: "click-na"
    nodes: [
     "10.60.11.241:8123",
     "10.60.11.242:8123",
     "10.60.11.243:8123",
    ]
    users:
      - name: "grafana"
        password: "***"

caches:
  - name: "shortterm"
    dir: "/tmp/cache"
    max_size: 150Mb
    expire: 600s
```

curl request to / of clickhouse node:

```
# curl -v 10.60.11.241:8123/
*   Trying 10.60.11.241...
* TCP_NODELAY set
* Connected to 10.60.11.241 (10.60.11.241) port 8123 (#0)
> GET / HTTP/1.1
> Host: 10.60.11.241:8123
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 16 May 2019 08:20:29 GMT
< Connection: Keep-Alive
< Keep-Alive: timeout=3
< Content-Type: text/html; charset=UTF-8
< Content-Length: 183
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 10.60.11.241 left intact
<html ng-app="SMI2"><head><base href="http://ui.tabix.io/"></head><body><div ui-view="" class="content-ui"></div><script src="http://loader.tabix.io/master.js"></script></body></html>
```

I think, simple request to '/' and search 'Ok' in body is not good for database healthcheck.
May be `SELECT 1;` request will be more suitable, because it always return predefined result.

For example:

```
# echo "SELECT 1;" | curl -u grafana:*** --data-binary @- 10.60.11.241:8123
1
```

### PR DESCRIPTION
**Pull request by levonet**
resolve #50

### CODE REVIEW

**Comment by valyala** [comment]
It would be better just sending `SELECT 1` query for the heartbeat under the first configured user for the given cluster without increasing the complexity of the config. This should resolve #50 .

**Comment by levonet** [comment]
Some complexity of the config needed because in clusters I can switching off some tables on one node. In this case, it will be convenient to check if some table exists.

For most cases, authorization is not necessary.

I can make query `select 1` by default. But I want to leave option not to use authorization or choose a user.

**Comment by levonet** [comment]
I don't see a pretty intermediate resolution between your proposal and my implementation.
If I'll find a time, I'll remove `to_user` in favor first user from `ClusterUsers`.

**Comment by levonet** [comment]
@valyala The first user from ClusterUsers is used for heart beat requests now.
And `select 1` request by default.

**Comment by levonet** [comment]
resolve #54

**Comment by levonet** [comment]
@hagen1778 ping

File: heartbeat.go [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+	"context"
+	"fmt"
+	"io/ioutil"
+	"net/http"
+	"time"
+
+	"github.com/Vertamedia/chproxy/config"
+)
+
+type heartBeat struct {
```
Comment (hagen1778) [inline heartbeat.go]: pls do `go fmt`

File: scope.go [hunk 2]
```diff
@@ -726,12 +726,20 @@ func newCluster(c config.Cluster) (*cluster, error) {
 		clusterUsers[cu.Name] = newClusterUser(cu)
 	}
 
+	if (len(c.ClusterUsers) == 0) {
```
Comment (hagen1778) [inline scope.go]: I guess this is already checked in `func (c *Config) UnmarshalYAML`

File: heartbeat.go [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+	interval time.Duration
+	timeout time.Duration
+	request string
+	response string
+	user string
+	password string
+}
+
+func newHeartBeat(c config.HeartBeat, firstClusterUser config.ClusterUser, oldInterval time.Duration) (*heartBeat, error) {
```
Comment (hagen1778) [inline heartbeat.go]: how the `error` could happen here?

File: heartbeat.go [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+
+	return newHB, nil
+}
+
+func (hb *heartBeat) isHealthy(addr string) error {
+	req, err := http.NewRequest("GET", addr + hb.request, nil)
+	if err != nil {
+		return err
+	}
+
```
Comment (hagen1778) [inline heartbeat.go]: extra line

File: config/config.go [hunk 5]
```diff
@@ -331,8 +342,11 @@ func (c *Cluster) UnmarshalYAML(unmarshal func(interface{}) error) error {
 	if c.Scheme != "http" && c.Scheme != "https" {
 		return fmt.Errorf("`cluster.scheme` must be `http` or `https`, got %q instead for %q", c.Scheme, c.Name)
 	}
-	if c.HeartBeatInterval == 0 {
-		c.HeartBeatInterval = Duration(time.Second * 5)
+	if c.HeartBeatInterval != 0 && c.HeartBeat.Interval != defaultHeartBeat.Interval {
+		return fmt.Errorf("cannot be use `heartbeat_interval` with `heartbeat.interval`")
+	}
+	if c.HeartBeat.Interval == 0 && c.HeartBeat.Timeout == 0 && c.HeartBeat.Response == "" {
+		return fmt.Errorf("`cluster.heartbeat` cannot be unset for %q", c.Name)
```
Comment (valyala) [inline config/config.go]: Does this mean that all the existing configs will break after upgrading to new version since they have no `HeartBeat` section?

File: config/config.go [hunk 6]
```diff
@@ -331,8 +342,11 @@ func (c *Cluster) UnmarshalYAML(unmarshal func(interface{}) error) error {
 	if c.Scheme != "http" && c.Scheme != "https" {
 		return fmt.Errorf("`cluster.scheme` must be `http` or `https`, got %q instead for %q", c.Scheme, c.Name)
 	}
-	if c.HeartBeatInterval == 0 {
-		c.HeartBeatInterval = Duration(time.Second * 5)
```
Comment (valyala) [inline config/config.go]: Does this mean that default value for heartbeat interval will change if it is unset in the config after the upgrade?

File: config/config_test.go [hunk 7]
```diff
@@ -80,7 +80,12 @@ func TestLoadConfig(t *testing.T) {
 								MaxExecutionTime:     Duration(time.Minute),
 							},
 						},
-						HeartBeatInterval: Duration(time.Minute),
```
Comment (valyala) [inline config/config_test.go]: I would leave tests for `HeartBeatInterval` without `HeartBeat` section in order to make sure all the existing configs won't break after the upgrade.

File: config/config.go (hunk 5 above)
Comment (levonet) [reply config/config.go]: All existing configs would be work.
But if you add `HeartBeat` section with `interval` it throws an error because it must be set once.

Comment (valyala) [reply config/config.go]: Then it would be great adding the corresponding tests, so this behavior doesn't accidentally break.

File: config/config.go (hunk 6 above)
Comment (levonet) [reply config/config.go]: This has already been done in `testdata/default_values.yml` section
https://github.com/Vertamedia/chproxy/pull/60/commits/36ba0b4400f59410ba3b9bce98ec22715dc71d4d#diff-bfeae88573cf9afa7638e19a4f7b4535R238

File: config/config.go (hunk 5 above)
Comment (levonet) [reply config/config.go]: It's being tested here.
- [old configuration](https://github.com/Vertamedia/chproxy/pull/60/files#diff-bfeae88573cf9afa7638e19a4f7b4535R83-R84)
- [new configuration](https://github.com/Vertamedia/chproxy/pull/60/files#diff-bfeae88573cf9afa7638e19a4f7b4535R127-R142)
- [errors](https://github.com/Vertamedia/chproxy/pull/60/files#diff-bfeae88573cf9afa7638e19a4f7b4535R424-R438)

File: config/config_test.go (hunk 7 above)
Comment (levonet) [reply config/config_test.go]: Done

**Comment by levonet** [comment]
@valyala Watch it again

**Comment by valyala** [comment]
Thanks
